### ISSUE TITLE
subaccount-consumer: SubaccountDerivativeConsumer fetchPositions() is returning DerivativeLimitOrder

### ISSUE THREAD

**Issue by starlabs007** [InjectiveLabs/injective-ts#1]
Hello, I noticed that in `SubaccountDerivativeConsumer.ts`, the `fetchPositions()` function is returning orders and not positions as expected.

`fetchPositions()` is actually using the same code as `fetchOrders()`.

**Comment by bangjelkoski** [comment]
You are right, the `fetchPositions()` function should not exist in this consumer. If you want to get Subaccount's position it has to go through the `fetchPositions()` function in the [DerivativeMarketConsumer.ts](https://github.com/InjectiveLabs/injective-ts/blob/dec443f2038d8c6819a1d362aac3ae9cf70e120e/packages/derivatives-consumer/src/consumers/DerivativeMarketConsumer.ts#L117) and pass the `subaccountId` as a parameter.
