### ISSUE TITLE
MsgMigrateContract not supported in sdk-ts

### ISSUE THREAD

**Issue by 0xfirefist** [InjectiveLabs/injective-ts#114]

**Comment by vianiGa** [comment]
Hello @0xfirefist have you been attended to ?

**Comment by 0xfirefist** [comment]
Hello @vianiGa, 
How can I use MsgMigrateContract in typescript?
As it is not supported in sdk-ts, I can work on a PR.

**Comment by bangjelkoski** [comment]
> Hello @vianiGa, 
> 
> How can I use MsgMigrateContract in typescript?
> 
> As it is not supported in sdk-ts, I can work on a PR.
> 
> 

Hey, the previous comment was from a scammer. I didn't know that they started scamming on Github nowadays.

Btw, happy to review a PR about the MsgMigrateContract msg :)

**Comment by 0xfirefist** [comment]
Woah okay, 
I raised a PR just know. @bangjelkoski

**Comment by vianiGa** [comment]
> > Hello @vianiGa, 
> > 
> > How can I use MsgMigrateContract in typescript?
> > 
> > As it is not supported in sdk-ts, I can work on a PR.
> > 
> > 
> 
> Hey, the previous comment was from a scammer. I didn't know that they started scamming on Github nowadays.
> 
> Btw, happy to review a PR about the MsgMigrateContract msg :)

Oh no @bangjelkoski i am not here to scam anyone 
I have interest about his/her post and I commented 
That doesn't make me scammer please correct that

**Comment by vianiGa** [comment]
@bangjelkoski that's so rude
