### ISSUE TITLE
feat: KujiraNetwork support

### ISSUE THREAD

**Issue by silvermind** [InjectiveLabs/injective-ts#125]
Would be great to have native IBC support to bridge INJ to the KujiraNetwork, as well as Kujira native denoms $KUJI and $USK to Injective.

A relayer is up: https://www.mintscan.io/injective/relayers/channel-98

similar to the osmo chain: https://github.com/InjectiveLabs/injective-ts/commit/26b33d7c0a1be5f79df9ba1960f188eb37031051 
Are these all the changes which are required in this repo?

related: https://github.com/InjectiveLabs/injective-dex/issues/993

**Comment by bangjelkoski** [comment]
Feel free to submit a PR.
