### ISSUE TITLE
error - ../../node_modules/@injectivelabs/wallet-ts/dist/esm/strategies/wallet-strategy/strategies/Ledger/Base.js:15:0

### ISSUE THREAD

**Issue by zpoken** [InjectiveLabs/injective-ts#176]
<img width="886" alt="Знімок екрана 2023-04-26 о 18 36 01" src="https://user-images.githubusercontent.com/82594516/234627357-beb6de39-20a6-4d4f-a8d0-64408140f489.png">

**Comment by M-Picco** [comment]
For the record, the root seems to be `alchemy-sdk@2.8.1`.

It can be worked around using `overrides` in your package file:

```
  "overrides": {
    "alchemy-sdk": "2.8.0"
  }
```
