### ISSUE TITLE
Error: Unsupported type: '/injective.types.v1beta1.EthAccount

### ISSUE THREAD

**Issue by zxl6866** [InjectiveLabs/injective-ts#219]
I encountered an error while trying to sign with the INJ using the Keplr wallet. Could you share how you resolved this?

I have a question to ask. I didn't encounter this error when creating a trading pair between JUNO and OSMO. However, when I tried creating a trading pair between OSMO and Injective, I encountered an error.
![image](https://github.com/InjectiveLabs/injective-ts/assets/134711504/604ae163-9221-4145-9213-f924935db627)

```ts
import { MsgExecuteContractEncodeObject } from '@cosmjs/cosmwasm-stargate';
import { toUtf8 } from '@cosmjs/encoding';
import { Coin } from '@cosmjs/stargate';
import { MsgExecuteContract } from 'cosmjs-types/cosmwasm/wasm/v1/tx';

type CreateExecuteMessageArgs = {
  senderAddress: string;
  message: any;
  contractAddress: string;
  funds?: Array<Coin>;
};

export const createExecuteMessage = ({
  senderAddress,
  contractAddress,
  message,
  funds,
}: CreateExecuteMessageArgs): MsgExecuteContractEncodeObject => ({
  typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
  value: MsgExecuteContract.fromPartial({
    sender: senderAddress,
    contract: contractAddress,
    msg: toUtf8(JSON.stringify(message)),
    funds: funds || [],
  }),
});
```

**Comment by bangjelkoski** [comment]
You can't use `cosmjs` to sign transactions on Injective. Read more here -> https://docs.ts.injective.network/readme/getting-started-cosmjs
