### ISSUE TITLE
"injective-ts error"：Uncaught ( in promise ) Typeerror : Cannot read properties of undefined ( reading ' length' )

### ISSUE THREAD

**Issue by zxl6866** [InjectiveLabs/injective-ts#220]
I referenced the documentation to write the code, and all the fields are there, but I've encountered an error. I've tried many methods to resolve it, but without success. Could you help me take a look? Thank you.

```ts
const msgs = MsgExecuteContractInjective.fromJSON({
    sender: accounts[0].address,
    contractAddress: getWasmChainIDContractAddress(
      remoteChain.chainID
    ) as string,
    // msg: toUtf8(JSON.stringify(takePoolMessages)),
    msg: takePoolMessages,
    funds,
  });

  // const msgs = MsgSend.fromJSON({
  //   amount,
  //   srcInjectiveAddress: accounts[0].address,
  //   dstInjectiveAddress: accounts[0].address,
  // });

  /** Get the PubKey of the Signer from the Wallet/Private Key */
  const pubKey = accounts[0].pubkey;

  console.log(remoteChain.chainID, 'remoteChain.chainID');
  console.log(msgs, 'msgs_____');
  console.log(pubKey, 'pubKey____');
  console.log(DEFAULT_STD_FEE, 'fee');
  console.log(accountDetails.sequence, 'accountDetails.sequence');
  console.log(accountDetails.accountNumber, 'accountDetails.accountNumber');

  /** Prepare the Transaction **/
  const { txRaw, signDoc } = createTransaction({
    chainId: remoteChain.chainID,
    message: msgs,
    memo: '',
    pubKey,
    fee: DEFAULT_STD_FEE,
    sequence: accountDetails.sequence,
    accountNumber: accountDetails.accountNumber,
    timeoutHeight: 100,
  });

  console.log(txRaw, 'txRaw______');

  const directSignResponse = await offlineSigner.signDirect(
    remoteAddress,
    signDoc
  );
  const txRawHx = getTxRawFromTxRawOrDirectSignResponse(directSignResponse);
  const txHash = await broadcastTx(remoteChain.chainID, txRawHx);
  const response = await new TxRestClient(remoteChain.rpcUrl).fetchTxPoll(
    txHash
  );

  console.log(response, 'response____');
```

![image](https://github.com/InjectiveLabs/injective-ts/assets/134711504/ef3e8687-cf99-45e5-b820-3d5b489270f0)
![image](https://github.com/InjectiveLabs/injective-ts/assets/134711504/cdc37ac2-b093-4511-8d95-e2b7eb799c48)
![image](https://github.com/InjectiveLabs/injective-ts/assets/134711504/d5b29116-09bc-4ae5-ac78-c7d120dda010)
![image](https://github.com/InjectiveLabs/injective-ts/assets/134711504/c59585f6-8971-4070-9a99-6b408458797c)
![image](https://github.com/InjectiveLabs/injective-ts/assets/134711504/f9a06ade-cdd6-42b9-914e-0c8a556f34f9)
Could not load content for http://127.0.0.1:5173/node_modules/@injectivelabs/sdk-ts/src/core/modules/tx/tx.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)

**Comment by altpd13** [comment]
I had the same issue just like you and I found out that publicKey was Uint8Array. 
The problem is that 'pubKey' parameter at createTransaction() should get publicKey in string not Uint8Array.
