### ISSUE TITLE
Question: Icon broken on our validator

### ISSUE THREAD

**Issue by rayanebel** [InjectiveLabs/injective-ts#231]
Hi everyone,

We did a PR last week [#229 ](https://github.com/InjectiveLabs/injective-ts/pull/229) to add an icon on our validator. The pR was merged but not sure if a new release of the hub has been done.

![Capture d’écran 2023-08-30 à 15 00 58](https://github.com/InjectiveLabs/injective-ts/assets/15887095/5111ff59-c3aa-4aca-aa1f-31fb1b7acfea)

https://hub.injective.network/validators/injvaloper1dyntafvjynns5zyltwgyktej0y5zt84y3npkt4/

**Comment by bangjelkoski** [comment]
Will update our hub now!
