### ISSUE TITLE
Can't fetch some tokens in fetchDenomMetadata

### ISSUE THREAD

**Issue by felipepimsil** [InjectiveLabs/injective-ts#327]
Hi, is `fetchDenomMetadata` method broken? Some `denoms` can not be fetched by this request.

Tried:
- `inj`
- `uinj`
- `factory-inj1xtel2knkt8hmc9dnzpjz6kdmacgcfmlv5f308w-ninja`

And I get:

```
{
  type: 'grpc-unary-request',
  code: -1,
  originalMessage: 'client metadata for denom inj',
  name: 'GrpcUnaryRequestException',
  errorClass: 'GrpcUnaryRequestException',
  context: 'DenomMetadata',
  contextModule: 'chain-bank'
}
```

I can only get some tokens metadata from the hardcoded option that is using `DenomClient`, but this does not seems right...

**Comment by bangjelkoski** [comment]
It's not broken, there are some assets that don't have metadata on the chain itself.
