### ISSUE TITLE
sdk-ts: running in nodejs

### ISSUE THREAD

**Issue by snack-0verflow** [InjectiveLabs/injective-ts#331]
Unable to run `@injectivelabs/sdk-ts` in a nodejs environment.

I've an example using `PrivateKey` from the sdk package to generate a wallet, which uses `bip34` under the hood to generate a private key. When used in nodejs either `cjs` or `esm` version works, unable to use `generate` function from `bip34` package import from transplied js code.

If there is example of using `@injectivelabs/sdk-ts` in nodejs environment that would be great

```
TypeError: Cannot read properties of undefined (reading 'generateMnemonic')
```

```js
// Example of the cjs code:
class PrivateKey {
    constructor(wallet) {
        this.wallet = wallet;
    }
    /**
     * Generate new private key with random mnemonic phrase
     * @returns { privateKey: PrivateKey, mnemonic: string }
     */
    static generate() {
        const mnemonic = bip39_1.default.generateMnemonic();
        const privateKey = PrivateKey.fromMnemonic(mnemonic);
        return {
            privateKey,
            mnemonic,
        };
    }
// .. rest of the code
```

[Stackblitz example](https://stackblitz.com/edit/stackblitz-starters-zv8sxy?file=dist%2Findex.js)

Run:
```sh
npm run start:js
# or npm run start:ts
```

**Comment by kgcdream2019** [comment]
There are one issue in PrivateKey module when you are going to use it in nodejs.
You can do as follows if you are going to generate random private keys:

```
import { PrivateKey } from "@injectivelabs/sdk-ts";
import * as bip39 from "bip39";
const mnemonic = bip39.generateMnemonic();
const privateKey = PrivateKey.fromMnemonic(mnemonic);
```

Above code is basically same as origin function of PrivateKey::generate.
Hope you are lucky!

**Comment by bangjelkoski** [comment]
> Unable to run `@injectivelabs/sdk-ts` in a nodejs environment.
> 
> I've an example using `PrivateKey` from the sdk package to generate a wallet, which uses `bip34` under the hood to generate a private key. When used in nodejs either `cjs` or `esm` version works, unable to use `generate` function from `bip34` package import from transplied js code.
> 
> If there is example of using `@injectivelabs/sdk-ts` in nodejs environment that would be great
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'generateMnemonic')
> ```
> 
> ```js
> // Example of the cjs code:
> class PrivateKey {
>     constructor(wallet) {
>         this.wallet = wallet;
>     }
>     /**
>      * Generate new private key with random mnemonic phrase
>      * @returns { privateKey: PrivateKey, mnemonic: string }
>      */
>     static generate() {
>         const mnemonic = bip39_1.default.generateMnemonic();
>         const privateKey = PrivateKey.fromMnemonic(mnemonic);
>         return {
>             privateKey,
>             mnemonic,
>         };
>     }
> // .. rest of the code
> ```
> 
> [Stackblitz example](https://stackblitz.com/edit/stackblitz-starters-zv8sxy?file=dist%2Findex.js)
> 
> Run:
> 
> ```shell
> npm run start:js
> # or npm run start:ts
> ```

I'll have a look, thanks for reporting I somehow missed the issue

**Comment by bangjelkoski** [comment]
This is resolved for a while.
