### ISSUE TITLE
NextJS 14.0.3

### ISSUE THREAD

**Issue by highree** [InjectiveLabs/injective-ts#368]
Hi, 

in my next app (ts) i use your sdk to retrieve staking and bank balances. Works great in dev mode, but compiling doesent work due to following error: 

Failed to compile.

```
./node_modules/@injectivelabs/token-metadata/dist/esm/index.js + 22 modules
Cannot get final name for export 'isIbcTokenCanonical' of ./node_modules/@injectivelabs/token-metadata/dist/esm/ibc/index.js
```

here a yarn info: 

❯ yarn info @injectivelabs/sdk-ts
└─ @injectivelabs/sdk-ts@npm:1.14.4
   ├─ Version: 1.14.4
   │ 
   └─ Dependencies
      ├─ @cosmjs/amino@npm:^0.30.1 → npm:0.30.1
      ├─ @cosmjs/proto-signing@npm:^0.30.1 → npm:0.30.1
      ├─ @cosmjs/stargate@npm:^0.30.1 → npm:0.30.1
      ├─ @ensdomains/ens-validation@npm:^0.1.0 → npm:0.1.0
      ├─ @ensdomains/eth-ens-namehash@npm:^2.0.15 → npm:2.0.15
      ├─ @ethersproject/bytes@npm:^5.7.0 → npm:5.7.0
      ├─ @injectivelabs/core-proto-ts@npm:^0.0.18 → npm:0.0.18
      ├─ @injectivelabs/dmm-proto-ts@npm:1.0.19 → npm:1.0.19
      ├─ @injectivelabs/exceptions@npm:^1.14.4 → npm:1.14.4
      ├─ @injectivelabs/indexer-proto-ts@npm:1.11.22 → npm:1.11.22
      ├─ @injectivelabs/mito-proto-ts@npm:1.0.52 → npm:1.0.52
      ├─ @injectivelabs/networks@npm:^1.14.4 → npm:1.14.4
      ├─ @injectivelabs/test-utils@npm:^1.14.3 → npm:1.14.3
      ├─ @injectivelabs/token-metadata@npm:^1.14.4 → npm:1.14.4
      ├─ @injectivelabs/ts-types@npm:^1.14.4 → npm:1.14.4
      ├─ @injectivelabs/utils@npm:^1.14.4 → npm:1.14.4
      ├─ @metamask/eth-sig-util@npm:^4.0.0 → npm:4.0.1
      ├─ axios@npm:^0.27.2 → npm:0.27.2
      ├─ bech32@npm:^2.0.0 → npm:2.0.0
      ├─ bip39@npm:^3.0.4 → npm:3.1.0
      ├─ cosmjs-types@npm:^0.7.1 → npm:0.7.2
      ├─ ethereumjs-util@npm:^7.1.4 → npm:7.1.5
      ├─ ethers@npm:^5.7.2 → npm:5.7.2
      ├─ google-protobuf@npm:^3.21.0 → npm:3.21.2
      ├─ graphql@npm:^16.3.0 → npm:16.8.1
      ├─ http-status-codes@npm:^2.2.0 → npm:2.3.0
      ├─ js-sha3@npm:^0.8.0 → npm:0.8.0
      ├─ jscrypto@npm:^1.0.3 → npm:1.0.3
      ├─ keccak256@npm:^1.0.6 → npm:1.0.6
      ├─ link-module-alias@npm:^1.2.0 → npm:1.2.0
      ├─ rxjs@npm:^7.8.0 → npm:7.8.1
      ├─ secp256k1@npm:^4.0.3 → npm:4.0.3
      ├─ shx@npm:^0.3.2 → npm:0.3.4
      ├─ snakecase-keys@npm:^5.4.1 → npm:5.5.0
      ├─ @apollo/client@npm:^3.5.8 → npm:3.8.8 [0991c]
      ├─ @injectivelabs/grpc-web-node-http-transport@npm:^0.0.2 → npm:0.0.2 [0991c]
      ├─ @injectivelabs/grpc-web-react-native-transport@npm:^0.0.2 → npm:0.0.2 [0991c]
      └─ @injectivelabs/grpc-web@npm:^0.0.1 → npm:0.0.1 [8d826]

i apreciate any help. 

edit:

using the beta release shows this: 

Failed to compile.

./node_modules/@injectivelabs/token-metadata/dist/esm/index.js + 23 modules
Cannot get final name for export 'devnetTokens' of ./node_modules/@injectivelabs/token-metadata/dist/esm/tokens/tokens/index.js

edit: 

this appears to only be a problem when using the sdk-ts in server components. I will investigate further with vercel next.

**Comment by bangjelkoski** [comment]
@ivan-angjelkoski thoughts?

**Comment by ivan-angjelkoski** [comment]
@highree are you using webpack or turbopack? did you try with both?
also its recommended to use vite react app instead of Next13-14 since it uses a new bundling method, which still needs improving.

**Comment by highree** [comment]
> @highree are you using webpack or turbopack? did you try with both? also its recommended to use vite react app instead of Next13-14 since it uses a new bundling method, which still needs improving.

**Comment by highree** [comment]
> Reference



> @highree are you using webpack or turbopack? did you try with both? also its recommended to use vite react app instead of Next13-14 since it uses a new bundling method, which still needs improving.

Hi Ivan, 

i managed to find out that i cannot use the sdk-ts in nextjs server components. But in an API-Route it works well. Weirdly it works well in dev env (next dev). But yarn build does not work with the error i mentioned. 

I end up using an api route, but in case someone manage to find out how to use this in server components i would be grateful.

**Comment by ivan-angjelkoski** [comment]
Yes, Server components break a lot of things... also keep in mind that you need to polyfill the node modules in your app, (crypto,buffer etc...) if we manage to make it somehow compatable we will post it in our [docs](https://docs.ts.injective.network/)
