### ISSUE TITLE
Reading isBuffer issue

### ISSUE THREAD

**Issue by iamthe-nerdyDev** [InjectiveLabs/injective-ts#373]
Hello, 

Tried executing a deposit message even from my frontend running on vite..but i keep getting this error:
WebProvider.tsx:219 TypeError: Cannot read properties of undefined (reading 'isBuffer')
    at toBuffer2 (chunk-EP2DLMQ2.js:5858:20)
    at keccak2569 (chunk-EP2DLMQ2.js:5854:15)
    at createTransactionWithSigners (chunk-EP2DLMQ2.js:372438:44)
    at createTransaction (chunk-EP2DLMQ2.js:372454:10)
    at MsgBroadcaster.broadcastWeb3 (MsgBroadcaster.ts:220:23)
    at async deposit (WebProvider.tsx:215:7)

The code: 
`
 async function deposit(amount: number) {
    try {
      if (!injectiveAddress) return Promise.reject();

      const msg = MsgExecuteContract.fromJSON({
        sender: injectiveAddress,
        contractAddress,
        msg: {
          deposit: {},
        },
        funds: [
          {
            denom: "inj",
            amount: new BigNumberInBase(amount).toWei().toFixed(),
          },
        ],
      });

      await msgBroadcastClient.broadcast({ msgs: msg, injectiveAddress });

      return Promise.resolve();
    } catch (e) {
      console.error(e);

      return Promise.reject();
    }
  }
`

Thanks

**Comment by iamthe-nerdyDev** [comment]
Sorry fixed it

**Comment by gitshahid3** [comment]
i face the same issue

**Comment by gitshahid3** [comment]
how did you solve the issue i need help @iamthe-nerdyDev

**Comment by iamthe-nerdyDev** [comment]
> how did you solve the issue i need help @iamthe-nerdyDev 

I guess you're working with vite + react yeah?

First install this package: 
````
npm install @bangjelkoski/vite-plugin-node-polyfills
````

Then edit your vite.config.ts to look like this:
```
import { defineConfig } from "vite";
// should be @vitejs/plugin-react-swc if you choose 'xxx + SWC' during app creation
import react from "@vitejs/plugin-react";
import { nodePolyfills } from "@bangjelkoski/vite-plugin-node-polyfills";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), nodePolyfills({ protocolImports: true })],
});

```

You can refer here if you need more clarification: [https://docs.ts.injective.network/building-dapps/configuring-react](https://docs.ts.injective.network/building-dapps/configuring-react)

That should work 💥

**Comment by gitshahid3** [comment]
thank you so much
