### ISSUE TITLE
DenomClientAsync getDenomToken does not work for some IBC tokens

### ISSUE THREAD

**Issue by kagenkoda** [InjectiveLabs/injective-ts#410]
For WOSMO token "ibc/DD648F5D3CDA56D0D8D8820CF703D246B9FC4007725D8B38D23A21FF1A1477E3" as per title above.

**Comment by bangjelkoski** [comment]
Are you using the latest packages and can I see a code snippet?

**Comment by kagenkoda** [comment]
`(async function main() {
  const denomClient = new DenomClientAsync(Network.MainnetSentry, {});

  const res = await denomClient.getDenomToken(
    "ibc/DD648F5D3CDA56D0D8D8820CF703D246B9FC4007725D8B38D23A21FF1A1477E3"
  );

  console.log(res);
})().then(() => {
  console.log("done");
});
`

I am using 1.14.5

**Comment by bangjelkoski** [comment]
Upgrade to at least 1.14.6 and try again.

**Comment by kagenkoda** [comment]
Works for me thanks
