### ISSUE TITLE
Possible wrong injective address derived from pubkey?

### ISSUE THREAD

**Issue by nooxx** [InjectiveLabs/injective-ts#468]
Hey,

I'm wondering why the derived injective address derived with the PublicKey class is different than the injective address onchain.

Example:

```typescript
const inj_address = 'inj19ndrue0wkh8pdxtnfmz7kg0p3pr7qm95rwwujl';
const rest_endpoint = getNetworkEndpoints(Network.MainnetSentry).rest;
const chain_rest_auth_api = new ChainRestAuthApi(rest_endpoint);
const account_details_response = await chain_rest_auth_api.fetchCosmosAccount(inj_address);
const base_account = BaseAccount.fromRestCosmosApi(account_details_response);

const pubkey = PublicKey.fromBase64(base_account.pubKey.key);
const derived_inj_address = pubkey.toAddress().toAccountAddress(); // inj19gpyz7tdwddehxhjlj8y8q09cnu0sg0xav3uvg
```

So I'm expecting `derived_inj_address` to be `inj19ndrue0wkh8pdxtnfmz7kg0p3pr7qm95rwwujl` but I'm getting `inj19gpyz7tdwddehxhjlj8y8q09cnu0sg0xav3uvg`

Could there be an issue in the PublicKey class?

**Comment by bangjelkoski** [comment]
How did you derive the initial injective address in the first place? We are using Ethereum-based derivation for the injective addresses not the default cosmos one.

**Comment by nooxx** [comment]
Makes sense, yeah the initial injective address was derived with cosmos derivation.
