### ISSUE TITLE
export 'InjectiveStargate' (imported as 'InjectiveStargate') was not found in '@injectivelabs/sdk-ts' (module has no exports)

### ISSUE THREAD

**Issue by rixhy-cyd** [InjectiveLabs/injective-ts#470]
After importing InjectiveStargate like

` import { InjectiveStargate } from '@injectivelabs/sdk-ts';`

i my code i get lot's of error like 

Module not found: Error: Can't resolve './core' in '/../../cypher/groot/node_modules/@injectivelabs/sdk-ts/dist/esm'
Did you mean 'index.js'?
BREAKING CHANGE: The request './core' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

Can anybody help me resolve it

**Comment by MbBrainz** [comment]
Same issue here. From version 1.14.7 to version 1.14.11 the `InjectiveStargate` is not exported anymore. This is a major breaking change I would say. Doesnt seem intentional. Even if it would be intentional, the docs do not reflect this change either. See [`using keplr`](https://docs.ts.injective.network/readme/getting-started-cosmjs#usage-using-keplr)

**Comment by bangjelkoski** [comment]
Import it from `@injectivelabs/sdk-ts/dist/exports`

**Comment by MbBrainz** [comment]
> Import it from `@injectivelabs/sdk-ts/dist/exports`

How is that a proper solution for the fact that your semantic versioning is wrong? It can cost people quite some time to figure out this issue. I would deprecate the release, fix your exports and then create a new proper release.

**Comment by bangjelkoski** [comment]
We will update the version once the chain upgrade is completed. 

Until then, you can use an old version of the packages. 

We are stil figuring out how to do proper semantic releases as there are tons of moving components related to the version of the packages.

**Comment by bangjelkoski** [comment]
We've published new stable versions:

```
@injectivelabs/exceptions: 1.14.12
@injectivelabs/networks: 1.14.12
@injectivelabs/sdk-ts: 1.14.12
@injectivelabs/ts-types: 1.14.12
@injectivelabs/utils: 1.14.12
@injectivelabs/wallet-ts: 1.14.12
```
