### ISSUE TITLE
Mixing cjs and esm imports results in duplicated version of the lib

### ISSUE THREAD

**Issue by HexiangLiu** [InjectiveLabs/injective-ts#471]
Hi, should lib-es be imported when building es modules? 
[filePath](https://github.com/InjectiveLabs/injective-ts/blob/dev/packages/wallet-ts/src/strategies/wallet-strategy/strategies/Ledger/Base.ts#L326)
<img width="595" alt="image" src="https://github.com/InjectiveLabs/injective-ts/assets/60799122/7849df7b-a228-4d07-aa6c-ddae20c735d8">

**Comment by bangjelkoski** [comment]
Yep, feel free to submit a PR

**Comment by HexiangLiu** [comment]
No problem

**Comment by bangjelkoski** [comment]
Appreciated. Keep in mind that we have to have the `commonjs` version as well for people who still use it

**Comment by HexiangLiu** [comment]
[https://github.com/InjectiveLabs/injective-ts/pull/472](https://github.com/InjectiveLabs/injective-ts/pull/472)
Here is the PR, thx
