### ISSUE TITLE
Support importing ES module

### ISSUE THREAD

**Issue by seven-feng** [InjectiveLabs/injective-ts#521]
Hi @bangjelkoski,

When using @injectivelabs/wallet-strategy@1.14.32, I noticed that there are two @ledgerhq/cryptoassets chunks, and they cannot be tree-shaken. I see that this issue was addressed previously in [this PR](https://github.com/InjectiveLabs/injective-ts/pull/472).

It seems that the problem arises due to the explicit inclusion of `/index.js` in:
`const ledgerService = await import('@ledgerhq/hw-app-eth/lib/services/ledger/index.js');`

Could you help fix this to ensure proper tree-shaking?

Thank you!

**Comment by bangjelkoski** [comment]
You should use `@injectivelabs/wallet-core` and add all of the wallets that you use - that way you can omit the Ledger wallet package and reduce the bundle size.

**Comment by seven-feng** [comment]
It seems I might not have expressed myself clearly. The issue I’m encountering is that my project uses the @injectivelabs/wallet-strategy package, but it references CommonJS (CJS). The replacement script didn’t take effect because the file name has changed.

<img width="908" alt="image" src="https://github.com/user-attachments/assets/a985ca4b-d59a-4e16-aaed-f5a686059bc8">

**Comment by bangjelkoski** [comment]
> The issue I’m encountering is that my project uses the @injectivelabs/wallet-strategy package

Question: You are using this instead of the `@injectivelabs/wallet-ts`? We've just released the new packages and they are not properly tested. 

I'll have a look at this btw.

**Comment by seven-feng** [comment]
Yes, it says that it has been deprecated.

<img width="717" alt="image" src="https://github.com/user-attachments/assets/d5373024-d40e-48df-9e6a-7a33ae67e54b">

**Comment by bangjelkoski** [comment]
```
Successfully published:
 - @injectivelabs/exceptions@1.14.33
 - @injectivelabs/networks@1.14.33
 - @injectivelabs/sdk-ts@1.14.33
 - @injectivelabs/test-utils@1.14.33
 - @injectivelabs/ts-types@1.14.33
 - @injectivelabs/utils@1.14.33
 - @injectivelabs/wallet-base@1.14.33
 - @injectivelabs/wallet-core@1.14.33
 - @injectivelabs/wallet-cosmos-strategy@1.14.33
 - @injectivelabs/wallet-cosmos@1.14.33
 - @injectivelabs/wallet-cosmostation@1.14.33
 - @injectivelabs/wallet-evm@1.14.33
 - @injectivelabs/wallet-ledger@1.14.33
 - @injectivelabs/wallet-magic@1.14.33
 - @injectivelabs/wallet-private-key@1.14.33
 - @injectivelabs/wallet-strategy@1.14.33
 - @injectivelabs/wallet-trezor@1.14.33
 - @injectivelabs/wallet-ts@1.14.33
 - @injectivelabs/wallet-wallet-connect@1.14.33
 ```

**Comment by hobadams** [comment]
Hey @bangjelkoski @seven-feng just picking this back up. I'm also seeing huge bundle sizes due to the wallet-strategy and/or the wallet-base package.   I'm running these versions of your packages:

```
"@injectivelabs/sdk-ts": "^1.14.45",
    "@injectivelabs/utils": "^1.14.48",
    "@injectivelabs/wallet-base": "^1.14.51",
    "@injectivelabs/wallet-strategy": "^1.14.51",
```

What was the solution in the end?

---

For more context my app is a React app build using vite and is client only (no node server).

**Comment by bangjelkoski** [comment]
> Hey [@bangjelkoski](https://github.com/bangjelkoski) [@seven-feng](https://github.com/seven-feng) just picking this back up. I'm also seeing huge bundle sizes due to the wallet-strategy and/or the wallet-base package. I'm running these versions of your packages:
> 
> ```
> "@injectivelabs/sdk-ts": "^1.14.45",
>     "@injectivelabs/utils": "^1.14.48",
>     "@injectivelabs/wallet-base": "^1.14.51",
>     "@injectivelabs/wallet-strategy": "^1.14.51",
> ```
> 
> What was the solution in the end?
> 
> For more context my app is a React app build using vite and is client only (no node server).

Hey, you can choose to use a particular set of wallets only using `wallet-core` without using `wallet-strategy` package. The `wallet-strategy` package includes all wallets that we support which is why it's expected that the bundle size is big. You can see an example here: https://github.com/InjectiveLabs/injective-ts/tree/master/packages/wallets/wallet-core
