### ISSUE TITLE
How to convert injective address to cosmos address?

### ISSUE THREAD

**Issue by 99Kies** [InjectiveLabs/injective-ts#528]

**Comment by bangjelkoski** [comment]
Read the docs https://docs.ts.injective.network/wallet/wallet-accounts#convert-cosmos-address-to-injective-address

**Comment by 99Kies** [comment]
@bangjelkoski  I tried it and it didn't meet my needs.
I want the address of the user's objective to be converted to the address of the cosmos in his wallet.
<img width="277" alt="image" src="https://github.com/user-attachments/assets/296978bf-9dc6-4a56-b47c-2955176df218">

**Comment by 99Kies** [comment]
<img width="347" alt="image" src="https://github.com/user-attachments/assets/a91ab65f-b34d-4ec5-8a62-69a78ee0b3a9">
<img width="346" alt="image" src="https://github.com/user-attachments/assets/6ac5439b-2636-4e75-8732-6cac1d7434da">

![image](https://github.com/user-attachments/assets/a0e6d350-b099-4445-84f7-876fd0e53e67)

@bangjelkoski As you can observe, going through the process in the documentation doesn't generate injective accounts that I can control. (I mean the injective account in keplr.)

**Comment by Fajjf** [comment]
Hello @99Kies  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
