### ISSUE TITLE
sdk-ts 1.0.150 is unusable

### ISSUE THREAD

**Issue by justinschuldt** [InjectiveLabs/injective-ts#81]
If you import the latest version of `@injectivelabs/sdk-ts`, version `1.0.150`, it throws 

```
Error: Cannot find module '@injectivelabs/indexer-api/injective_explorer_rpc_pb'
```

here is a minimal reproducer, it:
- creates a folder
- initializes an npm project
- installs `@injectivelabs/sdk-ts` version `1.0.150`
- adds a "start" script to package.json that invokes index.js
- imports `@injectivelabs/sdk-ts` into index.js
- runs the index.js

tested with
`node v16.17.0`
`npm 8.15.0`

```bash
mkdir package-fails && cd package-fails && \
npm init -y && \
npm i @injectivelabs/sdk-ts@1.0.150 -S && \
npm set-script start "node index.js" && \
echo "const sdk = require('@injectivelabs/sdk-ts'); console.log('hello world from index.js');" > index.js && \
npm run start
```

Here is a minimal reproducer of a previous version (`1.0.75`) working:

```bash
mkdir package-works && cd package-works && \
npm init -y && \
npm i @injectivelabs/sdk-ts@1.0.75 @injectivelabs/indexer-api@1.0.2 -S --save-exact && \
npm set-script start "node index.js" && \
echo "const sdk = require('@injectivelabs/sdk-ts'); console.log('hello world from index.js');" > index.js && \
npm run start
```

It seems that because your packages have carrots (`^`) on the dependencies, and you only increment the `PATCH` part of [semver](https://semver.org/), npm will always pull the latest version of everything and always pickup breaking changes.

**Comment by bangjelkoski** [comment]
I'll have a look today, thanks for making the issue!

**Comment by bangjelkoski** [comment]
This should work fine now, I've updated the codebase and republished the package

```
Successfully published:
 - @injectivelabs/sdk-ts@1.0.151
```
